### ISSUE TITLE
Is there a possibility to manipulate existing nodes

### ISSUE THREAD

**Issue by opensource21** [jmurty/java-xmlbuilder#16]
The builder can parse existing documents and find specific elements. Then you can add attributes or child-element. I wonder if it is possible to remove an attribute or a element from the dom?

**Comment by jmurty** [comment]
Hi, since the builder is focussed on building documents it only allows for additive changes. You can however access the underlying DOM elements and use standard methods to manipulate the element that way. For example, you could do something like `builderNode.getElement().removeAttribute("unwanted")`.

See https://github.com/jmurty/java-xmlbuilder#accessing-the-underlying-document

**Comment by reitzig** [comment]
FYI: Got here with the usage "create valid test data in a helper method, then make changes (to text in some element) in the test method". So, in a way, I _want_ a "two-phase" builder.
